version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../..:/workspaces:cached
      - ../.env:/app/.env:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
    shm_size: 1gb
    user: vscode
